### ISSUE TITLE
controls.js-5.0.0.zip directory issues

### ISSUE THREAD

**Issue by siims-biz** [controlsjs/controls.js#1]
Hello,
the downloadable source code at github
controls.js-5.0.0.zip
seems to be incompatible with the hello world sample
https://controlsjs.com/howto/basics-helloworld.html
The folders and script file naming are not the same.
Maybe you could include a working sample in git.

**Comment by tulach** [comment]
Hello,
the hello world example is compatible with downloadable source controls.js-5.0.0.zip. This means that provided source code of hello world example runs without any errors with this release.

To make it work you have to build controls.js from sources (how to do it is described here - https://github.com/controlsjs/controls.js) and then just put files from "controlsjs-5.0.0\build\release\5.0.0\" into "controls.js\release" folder, relative to index.html and main.js mentioned in the hello world example.

You don't need to build controls.js from sources and have more examples if you use our download section on controlsjs.com web site - http://controlsjs.com/downloads/. See Compare Versions.

The most easiest way how to get the hello world example is to use our integration with NetBeans IDE and just create new project with sample code. How to do it is described in How-Tos on our website or you can watch our video tutorial here - https://www.youtube.com/watch?v=KAoq0VFO-8M

Jiří Tulach
Controls.js Team
